### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JulienRe** [ricetech/csgo-match-tracker#1]
Hello,
 Can you provide a screenshot of the result please?
Thank you.

**Comment by ricetech** [comment]
Hello, which result are you looking for?

**Comment by JulienRe** [comment]
Hello,
I would love to see what your software does...
I do not quite understand what is the purpose of what you put in your python file.

**Comment by ricetech** [comment]
Sure. Here are a few screenshots:
[image: image.png]
[image: image.png]
[image: image.png]

I plan on creating a README containing more detailed instructions and
pictures once I have some free time. It will be available in the GitHub
repository once it's ready.

**Comment by JulienRe** [comment]
> Sure. Here are a few screenshots: [image: image.png] [image: image.png] [image: image.png] I plan on creating a README containing more detailed instructions and pictures once I have some free time. It will be available in the GitHub repository ,(...)

Cool :)

i'm sorry i can't see your pictures :(
https://zupimages.net/up/20/20/ao31.jpg

**Comment by ricetech** [comment]
Here are the images:
![image](https://user-images.githubusercontent.com/39015447/82136265-be064200-97d9-11ea-92d6-94e617c6bf2a.png)
![image](https://user-images.githubusercontent.com/39015447/82136266-c6f71380-97d9-11ea-8bc8-cdc8354087ba.png)
![image](https://user-images.githubusercontent.com/39015447/82136267-ca8a9a80-97d9-11ea-8699-54ec1d5a9948.png)
